version: '3.9'

services:
  dev:
    container_name: face-recognition-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./models:/app/models
    ports:
      - "3001:3001"        
    networks:
      - sale_net
    command: uvicorn api1:app --host 0.0.0.0 --port 3000 --reload
    restart: unless-stopped

networks:
  sale_net:
    driver: bridge
